var ghost_fs = ["uniform vec4 diffuseColor;",
				"uniform sampler2D ghostMap;",
				"uniform float ghostParam;",
				"uniform float ghostTime;",
				"varying vec4 v_pos;",
				"varying vec3 a_pos;",
				"varying vec3 v_norm;",

				"void main() {",
				"	vec3 viewdir = -normalize(v_pos.xyz);",
				"	vec3 nnorm  = normalize(v_norm);",
				"	float gval = clamp(dot(viewdir, nnorm), 0.01, 0.99);",
				"	vec2 samppos = vec2(gval, ghostParam);",
				"	vec4 maskVal = vec4(gval, gval, gval, 1.0); //texture2D(ghostMap, samppos);",
				"   float rad = sqrt(a_pos.x*a_pos.x + a_pos.y*a_pos.y);",
				"   float theta = atan(a_pos.z, a_pos.y) + rad*5.0*sin(rad*10.0);",
				"   float theval = sin(ghostTime + theta * 7.0); // * sin(rad*3.0);",
				"   if(theval < 0.0) discard;",
				"	gl_FragColor = vec4(diffuseColor.rgb * maskVal.rgb, 1.0);",
				"}"].join("\n");

var ghost_vs = ["varying vec4 v_pos;",
				"varying vec3 v_norm;",
				"varying vec3 a_pos;",
				"void main() {",
				"a_pos = position;",
				"v_pos = modelViewMatrix * vec4( position, 1.0 );",
				"v_norm = normalMatrix * normal;",
				"gl_Position = projectionMatrix * v_pos;",
				"}"].join("\n");
